library(MASS)
data(Boston)
print(names(Boston))
print(head(Boston))
fix(Boston)
print(summary(Boston))
write.csv(Boston, "Boston.csv", row.names = F)
attach(Boston)
lm.fit=lm(medv~lstat)
print(summary(lm.fit))
print(names(lm.fit))
print(coef(lm.fit))
print(confint(lm.fit))
print(predict(lm.fit,data.frame(lstat=(c(5,10,15))), interval="confidence"))
print(predict(lm.fit,data.frame(lstat=(c(5,10,15))), interval="prediction"))
pdf("BostonStats.pdf")
plot(lstat,medv,col="blue",pch=10)
abline(lm.fit)
abline(lm.fit,lwd=5,col="red")
plot(1:25,1:25,pch=1:25)
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict(lm.fit), residuals(lm.fit))
plot(hatvalues(lm.fit), rstudent(lm.fit))
dev.off()
lm.fit=lm(medv~.,data=Boston)
print(summary(lm.fit))
lm.fit1=lm(medv~.-age-indus,data=Boston)
print(summary(lm.fit1))
