BostonStats <- function() {
  library(MASS)
  data(Boston)
  names(Boston)
  head(Boston)
  fix(Boston)
  summary(Boston)
  write.csv(Boston, "Boston.csv", row.names = F)
  attach(Boston)
  lm.fit=lm(medv~lstat)
  summary(lm.fit)
  names(lm.fit)
  coef(lm.fit)
  confint(lm.fit)
  predict(lm.fit,data.frame(lstat=(c(5,10,15))), interval="confidence")
  predict(lm.fit,data.frame(lstat=(c(5,10,15))), interval="prediction")
  pdf("BostonStats.pdf")
  plot(lstat,medv,col="blue",pch=10)
  abline(lm.fit)
  abline(lm.fit,lwd=5,col="red")
  plot(1:25,1:25,pch=1:25)
  par(mfrow=c(2,2))
  plot(lm.fit)
  plot(predict(lm.fit), residuals(lm.fit))
  plot(predict(lm.fit), rstudent(lm.fit))
  plot(hatvalues(lm.fit))
  dev.off()
  which.max(hatvalues(lm.fit))
}
